enum cmd_types{REGULAR=0, OUTPUT_REDIRECT, INPUT_REDIRECT, PIPE, BACKGROUND, DOG};
char *pwd();
char *sh_readline();
char **split(char *str, char *tok);
int get_size(char **line);
//int normal_execute(int argc, char **line);
int normal_execute(char **cmd_cpy);
//int what_command(int argc, char **argv);
int what_command(char **cmd_cpy);
int getIndxOf(char *delim, int argc, char **argv);
int output_redir(char *line);
int input_redir(char *line);
int pipe_cmd(char* line);
int background_cmd(char *line);
